# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SkillValidator < Formula
  desc "CLI tool that validates and scores Agent Skill packages"
  homepage "https://github.com/dacharyc/skill-validator"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dacharyc/skill-validator/releases/download/v0.5.1/skill-validator_0.5.1_darwin_amd64.tar.gz"
      sha256 "69d09f502860ca823400f81cc21f02ed0a5179f2f38108d2da2dcdc66df93e34"

      def install
        bin.install "skill-validator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dacharyc/skill-validator/releases/download/v0.5.1/skill-validator_0.5.1_darwin_arm64.tar.gz"
      sha256 "99eb8a4799fbea694f943c064e8fa8e15d95232190eae492172998c8777ac02c"

      def install
        bin.install "skill-validator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dacharyc/skill-validator/releases/download/v0.5.1/skill-validator_0.5.1_linux_amd64.tar.gz"
      sha256 "e14769391acb864bf9365afd9d085834cf76c81a27af25b929231576170dd499"
      def install
        bin.install "skill-validator"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dacharyc/skill-validator/releases/download/v0.5.1/skill-validator_0.5.1_linux_arm64.tar.gz"
      sha256 "2ae78974b7e306e63d0084e2dbc4ecf1009ae550a3a9be67a455ff369b4a8a59"
      def install
        bin.install "skill-validator"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/skill-validator --version")
  end
end
