# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SkillValidator < Formula
  desc "CLI tool that validates and scores Agent Skill packages"
  homepage "https://github.com/dacharyc/skill-validator"
  version "0.8.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dacharyc/skill-validator/releases/download/v0.8.1/skill-validator_0.8.1_darwin_amd64.tar.gz"
      sha256 "66a3ae775d24b915bf451b1ad7677be1e368da4d25690f26f9f95a6bc2304816"

      define_method(:install) do
        bin.install "skill-validator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dacharyc/skill-validator/releases/download/v0.8.1/skill-validator_0.8.1_darwin_arm64.tar.gz"
      sha256 "91a973af83f0dcd1000547b7fd33097896f2be73e347117f59c080cb0c649c43"

      define_method(:install) do
        bin.install "skill-validator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dacharyc/skill-validator/releases/download/v0.8.1/skill-validator_0.8.1_linux_amd64.tar.gz"
      sha256 "3afae11a60bd48ed3582ff09e8387a856b1a7eaa79feaef6aa61fba5d4b754d2"
      define_method(:install) do
        bin.install "skill-validator"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dacharyc/skill-validator/releases/download/v0.8.1/skill-validator_0.8.1_linux_arm64.tar.gz"
      sha256 "6dc27f133ea3038b37f68db8eb987cd588636fcb52c404d511902423b811898f"
      define_method(:install) do
        bin.install "skill-validator"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/skill-validator --version")
  end
end
